from pathlib import Path
import json
p=Path('.')
def edit(name, pairs):
 f=p/name;s=f.read_text(encoding='utf-8');
 for a,b in pairs:
  if a not in s: print('MISSING',name,a[:50])
  s=s.replace(a,b)
 f.write_text(s,encoding='utf-8')
(p/'src/lib/brand.json').write_text(json.dumps(dict(ivory='#F3EBDD',chocolate='#4A3327',terracotta='#B85126',teal='#0F4A58',warmGold='#E0A03F',brass='#EBC86A',charcoal='#4C4C4C'),indent=2)+'\n')
f=p/'src/styles/theme.ts';s=f.read_text(); start=s.index('export const color'); s='/** Exact namecard identity; semantic surfaces below derive from these seven colors. */\nimport brand from "../lib/brand.json";\nexport const palette = brand;\n\n'+s[start:]
for a,b in [('palette.deepBrown','palette.chocolate'),('palette.cream','palette.ivory'),('palette.gold','palette.brass'),('palette.sand','"color-mix(in srgb, #EBC86A 20%, #F3EBDD)"'),('body: "#514336"','body: palette.charcoal'),('59, 41, 29','74, 51, 39'),('184, 83, 39','184, 81, 38'),('243, 235, 222','243, 235, 221'),('maxWidth: "1312px"','maxWidth: "1280px"'),('gutter: "clamp(22px, 5vw, 80px)"','gutter: "clamp(20px, 5.556vw, 80px)"'),('eyebrow: "0.8125rem"','eyebrow: "0.6875rem"'),('caption: "0.875rem"','caption: "0.8125rem"'),('base: "clamp(1.125rem, 1.05rem + 0.15vw, 1.1875rem)"','base: "clamp(1.0625rem, 1rem + 0.14vw, 1.125rem)"')]:s=s.replace(a,b)
s=s.replace('export const color = {','export const color = {\n  teal: palette.teal,\n  tealWash: `color-mix(in srgb, ${palette.teal} 8%, ${palette.ivory})`,\n  warmGold: palette.warmGold,')
s=s.replace('"color-mix(in srgb, #EBC86A 20%, #F3EBDD)"','`color-mix(in srgb, ${palette.brass} 20%, ${palette.ivory})`')
f.write_text(s,encoding='utf-8')
edit('src/pages/site/system.tsx', [('min(1312px','min(1280px'),('font: 600 13px/1.45','font: 600 11px/1.45'),('letter-spacing: 0.105em','letter-spacing: 0.16em'),('clamp(44px, 4.9vw, 76px)/1.035','clamp(42px, 5.28vw, 76px)/0.98'),('clamp(19px, 1.65vw, 23px)','clamp(18px, 1.4vw, 20px)'),('clamp(62px, 7vw, 112px)','clamp(76px, 8vw, 116px)'),('font: 400 19px/1.6','font: 400 18px/1.65'),('font: 600 13px/1.4','font: 600 11px/1.4'),('letter-spacing: 0.1em','letter-spacing: 0.16em'),('clamp(44px, 5.1vw, 76px)','clamp(42px, 5.28vw, 76px)'),('clamp(20px, 1.7vw, 24px)','clamp(18px, 1.4vw, 20px)')])
edit('src/components/ui/primitives.ts',[('font-size: ${type.sm};\n    font-weight: ${weight.semibold};','font-size: 15px;\n    font-weight: ${weight.semibold};'),('primary: css`\n        background: ${color.primary};','primary: css`\n        background: ${color.accent};'),('background: ${color.primaryHover};\n            box-shadow: ${shadow.sm};','background: ${color.accentHover};\n            box-shadow: ${shadow.sm};')])
edit('src/pages/site/Header.tsx',[('window.scrollY > 32','window.scrollY > 56'),('<div className="gf-nav-inner">','<div className="announcement"><span>Opening to a few families at a time — so every first call is one we can stand behind</span> <Link to="/start" onClick={close}>Join the waitlist →</Link></div>\n      <div className="gf-nav-inner">'),('location.pathname + location.hash === to','location.pathname === to')])
edit('src/pages/site/chrome.styles.ts',[('background: ${color.paper};','background: ${color.ivory};'),('min(1440px','min(1280px'),('min(1312px','min(1280px'),('min-height: 80px','min-height: 74px'),('min-height: 70px','min-height: 68px'),('font-size: 17px;','font-size: 15px;'),('gap: clamp(24px, 2.8vw, 42px)','gap: 34px'),('gap: 42px;','gap: 34px;'),('${buttonBase} ${buttonVariants.primary}min-height:48px;','${buttonBase} ${buttonVariants.brown}min-height:48px;'),('font-size: 16px;\n  }\n  .gf-menu-toggle','font-size: 15px;\n    border-radius: 8px;\n  }\n  .gf-menu-toggle'),('grid-template-columns: repeat(3, 1fr);','grid-template-columns: repeat(4, 1fr);')])
f=p/'src/pages/site/chrome.styles.ts';s=f.read_text();s=s.replace('  position: sticky;','  .announcement { background: ${color.teal}; color: ${color.onDark}; min-height: 28px; display: flex; justify-content: center; align-items: center; flex-wrap: wrap; gap: 3px 12px; padding: 4px 20px; font: 400 11.5px/1.5 ${font.body}; text-align: center; }\n  .announcement a { color: ${color.gold}; text-underline-offset: 3px; }\n  &.is-scrolled { background: color-mix(in srgb, ${color.ivory} 96%, transparent); backdrop-filter: blur(8px); }\n  @media(max-width:640px) { .announcement { padding: 6px 20px; } }\n  position: sticky;',1);s=s.replace('  .gf-footer-links a {','  .gf-footer-links h2 { color: ${color.gold}; font: 600 11px ${font.body}; letter-spacing: .12em; margin-bottom: 12px; }\n  .gf-footer-links a {');f.write_text(s,encoding='utf-8')
