from pathlib import Path
p=Path('src/pages/site/shared.tsx');s=p.read_text(encoding='utf-8');a=s.index('import {\n  SIMPLE_NAME');b=s.index('import { color',a);s=s[:a]+'import Logo from "../../components/ui/Logo";\n'+s[b:];a=s.index('const Mark =');b=s.index('const Figure =',a);s=s[:a]+'''export function Wordmark({light=false}:{light?:boolean}) { return <Logo height={44} tone={light?'dark':'light'}/>; }
'''+s[b:];s=s.replace('<Invite $paper>','<Invite $dark style={{background:color.teal}}>');s=s.replace('<Label>A place to begin</Label>','<Label style={{color:color.warmGold}}>Start the record</Label>');s=s.replace('The stories worth keeping\n            <br />\n            <em>are already happening.</em>','The best day to begin <br />\n            <em>is an ordinary one.</em>');s=s.replace('<Intro>Start with a conversation.</Intro>','<Intro>A twenty-minute conversation — then a lifetime of stories, organized and yours, with room left for all the ones still to come.</Intro>');s=s.replace('Explore the experience','See how it works');s=s.replace('<Label>From the archive, into your hands</Label>','<Label>The book</Label>');s=s.replace('A chapter you\n                <br />\n                can <em>hold.</em>','Any chapter can become <em>something you hold.</em>');s=s.replace('Choose stories and photographs from your living archive for a\n                physical volume. Something to pass around the table.','When you are ready — not when a deadline says so — a chapter is edited, laid out like a memoir and printed as a hardcover book, with the photographs beside the stories they belong to.');s=s.replace('<p className="book-note">\n                The book can be finished.\n                <br />\n                The story isn’t.\n              </p>','<Intro>The book is the edited version. The archive keeps the rest: every transcript, every recording, and everything that did not fit on the page.</Intro><p className="book-note">And the story does not stop when the book is made. It keeps going, because so do you.</p>');s=s.replace('font-size: 26px;\n    margin: 0;','font-family: ${font.body};\n    font-style: normal;\n    font-size: 18px;\n    margin: 0;');p.write_text(s,encoding='utf-8')
p=Path('src/pages/site/Footer.tsx');s=p.read_text(encoding='utf-8');a=s.index('          <div className="gf-footer-links">');b=s.index('        <div className="gf-footer-bottom">',a);s=s[:a]+'''          <div className="gf-footer-links">
            <div><h2>PRODUCT</h2><Link to="/how-it-works">How it works</Link><Link to="/for-families">For families</Link><Link to="/pricing">Pricing</Link><Link to="/guides">Conversation guides</Link></div>
            <div><h2>OTHER USES</h2><Link to="/care-communities">Care communities</Link><Link to="/organizations">Organizations</Link><Link to="/for-families#your-own-story">Your own story</Link></div>
            <div><h2>COMPANY</h2><Link to="/our-story">Our story</Link><Link to="/questions">Questions & answers</Link><a href={CONTACT.general}>Get in touch</a></div>
            <div><h2>LEGAL / ACTION</h2><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/start">Join the waitlist</Link></div>
          </div>
        </div>
'''+s[b:];s=s.replace('<Wordmark light />','<Wordmark light /><p className="brand-descriptor">Your Family’s Living Memories</p>');p.write_text(s,encoding='utf-8')
