from pathlib import Path
p=Path('src/pages/site/Home.tsx');s=p.read_text(encoding='utf-8');a=s.index('const Memory =');b=s.index('const Voices =',a);m=s[a:b].replace('function MemoryExample()','export default function MemoryExample()');m=m.replace('We can’t see what','We cannot see what');m=m.replace('<h3>{sampleMemory.question}</h3>','<div className="exchange"><span>A Story</span><p>“{sampleMemory.question}”</p></div>');m=m.replace('A Story follows the detail','A Story');m=m.replace('<p style={{ marginTop: 14 }}>','<p style={{ marginTop: 14 }}>');m=m.replace('              <Actions>\n                <ButtonEl\n                  onClick', '              <p className="method-note">A Story follows the feeling she introduced instead of moving to the next prepared question.</p>\n              <Actions>\n                <ButtonEl\n                  onClick');m=m.replace('<Label>03 / A memory with its context</Label>','<Label>03 / The card</Label>');m=m.replace('<summary>Read the original exchange</summary>','<summary>Full transcript</summary><p>A Story: “{sampleMemory.question}”</p>');m=m.replace('              <Actions>\n                <TextLink as={Link}', '''              <div className="voice-layer"><span>VOICE HIGHLIGHT</span><blockquote>“{sampleMemory.openingWords}”</blockquote><small>Illustrated layer · no audio recording in this example.</small></div><p className="layer-path">Card → full transcript → voice highlight.</p>
              <Actions>
                <TextLink as={Link}''');m=m.replace('  .memory-copy details {','  .method-note { margin-top: 20px; font-size: 15px !important; color: ${color.teal}; }\n  .voice-layer { background: ${color.teal};color:${color.onDark};padding:18px;margin-top:18px;border-radius:8px; }\n  .voice-layer span {font-size:11px;color:${color.warmGold};}\n  .voice-layer blockquote {font:italic 24px/1.4 ${font.display};margin:10px 0;}\n  .voice-layer small,.layer-path {font-size:12.5px;margin-top:12px;}\n  .memory-copy details {');m=m.replace('background: ${color.primary};\n    color: ${color.onDark};','background: ${color.teal};\n    color: ${color.onDark};');Path('src/pages/site/MemoryExample.tsx').write_text('''import {useState} from 'react';
import {Link} from 'react-router-dom';
import styled from 'styled-components';
import {ButtonEl} from '../../components/ui/primitives';
import {sampleMemory} from '../../lib/sampleMemory';
import {color,font,media,motion} from '../../styles/theme';
import {Photo} from './shared';
import {Label,Actions,TextLink} from './system';
'''+m,encoding='utf-8')
p=Path('src/lib/sampleMemory.ts');s=p.read_text(encoding='utf-8');s=s.replace('/** One fictional record underlies every website demonstration.','/** The lake example is separate from the clearly labeled Joan/Rosa/Errol demonstrations.');s=s.replace('What do you remember about this afternoon?','What do you remember about that afternoon at the lake?').replace('I remember Daniel running straight into the water…','I remember being terrified.').replace('You stayed on the shore. What were you worried about?','What were you afraid would happen?').replace('From the shore, I couldn’t tell how deep the water was.','He thought he was playing. I thought I had let him go too far.').replace('I was terrified that whole afternoon.','I remember being terrified.').replace('It was the best day of that summer.','I thought it was an adventure.').replace('I’ve been told this story my whole life.','That story got told every year.');p.write_text(s,encoding='utf-8')
