import fs from 'node:fs';import sharp from 'sharp';import crypto from 'node:crypto';
const entries=[['desktop','C:/Users/vngia/.codex/generated_images/01a0a2cc-35cb-7843-8ee8-7f80e729f1f6/exec-d749cef9-0953-4b8d-be31-0ea3e7720a92.png',"Use case: photorealistic editorial documentary. Asset type: illustrative A Story care-community webpage photo, 3:2 landscape. An older woman late 70s/early 80s is the active storyteller at a small table in an ordinary senior-living community lounge. She holds an ordinary family print toward an adult daughter 45–55 who listens attentively; a life-enrichment staff member in everyday clothing sits slightly behind, listening rather than leading. Small group of loose prints on table. Natural window light, slightly mixed ambient lighting, believable lived-in furniture. 35mm slightly off-axis documentary framing. Quiet engaged thoughtful expressions, anatomically correct visible hands. Keep people close enough together that a later 4:5 mobile composition can retain all three. Some negative space on one side. No text, logos, hospital, scrubs, stethoscope, wheelchairs as age-signals, forced touching, fake laughter, camera-facing smiles, coordinated clothing, symmetry, luxury resort styling, sentimental hug, prominent clipboard, stock advertising polish. The scene should feel observed."],['mobile','C:/Users/vngia/.codex/generated_images/01a0a2cc-35cb-7843-8ee8-7f80e729f1f6/exec-4ce25fb9-a868-4350-ba8b-20ef78f62417.png',"Recompose this exact illustrative documentary care-community scene into a 4:5 portrait photograph for mobile. Preserve the same three people and clothes: the older woman is the active storyteller holding the photograph, daughter listening, staff member secondary. Retain all three faces, the photograph and plausible visible hands. Move framing and camera distance naturally to fit the people; do not crop anyone's face off. Same ordinary lounge, light and documentary perspective, no text or logo, no added people, no medical cues."]];
let registry=JSON.parse(fs.readFileSync('src/lib/assetRegistry.json','utf8'));
console.log(Array.isArray(registry)?'array':Object.keys(registry));
const records=[];
for(const [kind,source,prompt] of entries){const dest='qa/generated/ASTORY_CARE_'+kind.toUpperCase()+'.png';fs.copyFileSync(source,dest);const metadata=await sharp(dest).metadata();const derivatives=[];for(const width of(kind==='desktop'?[640,1200,1536]:[640,1200])){const path='public/supplements/care-'+kind+'-'+width+'.webp';const info=await sharp(dest).resize({width,withoutEnlargement:true}).webp({quality:88}).toFile(path);derivatives.push({file:path,width:info.width,height:info.height});}records.push({id:'care-'+kind,source:dest,sha256:crypto.createHash('sha256').update(fs.readFileSync(dest)).digest('hex'),width:metadata.width,height:metadata.height,prompt,derivatives,status:'generated illustrative scene',placement:['Home audience selector','Care communities'],alt:'An older woman shares a family photograph with her daughter and a community staff member',caption:'Archive photographs and demonstration memories are illustrative.'});}
fs.writeFileSync('qa/care-assets.json',JSON.stringify(records,null,2));
if(Array.isArray(registry)){registry=registry.filter(x=>!String(x.id).startsWith('care-')).concat(records);fs.writeFileSync('src/lib/assetRegistry.json',JSON.stringify(registry,null,2));}


if(!Array.isArray(registry)){for(const record of records)registry[record.id]=record;fs.writeFileSync("src/lib/assetRegistry.json",JSON.stringify(registry,null,2));}
