/**
 * Converts the source photography in src/assets to WebP.
 *
 * The originals are multi-megabyte PNGs of photographs — the worst possible
 * format for the job. At 1600px and quality 76 they land around 5% of the
 * original weight with no visible difference at any size the site renders
 * them. Originals are left in place; components import the .webp.
 *
 * Run with `npm run images`. Idempotent — existing .webp files are skipped
 * unless the PNG is newer.
 */
import { readdirSync, statSync } from 'node:fs';
import { dirname, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const assets = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'assets');

/** Logos and UI chrome stay lossless; photographs get the lossy treatment. */
const LOSSLESS = new Set(['darkLogo', 'lightLogo']);

/** Generated by scripts/brand-assets.mjs — never regenerate these from the PNG. */
const SKIP = new Set(['astoryDaniel', 'astoryBao']);
const MAX_WIDTH = 1600;

const files = readdirSync(assets).filter((f) => ['.png', '.jpg', '.jpeg'].includes(extname(f).toLowerCase()));

let saved = 0;
for (const file of files) {
    const name = file.replace(/\.[^.]+$/, '');
    const src = join(assets, file);
    const out = join(assets, `${name}.webp`);

    const srcStat = statSync(src);
    try {
        if (statSync(out).mtimeMs >= srcStat.mtimeMs) continue;
    } catch {
        /* no existing output — convert */
    }

    const image = sharp(src);
    const { width } = await image.metadata();

    await image
        .resize({ width: Math.min(width ?? MAX_WIDTH, MAX_WIDTH), withoutEnlargement: true })
        .webp(LOSSLESS.has(name) ? { lossless: true } : { quality: 76, effort: 5 })
        .toFile(out);

    const after = statSync(out).size;
    saved += srcStat.size - after;
    console.log(
        `${file.padEnd(28)} ${(srcStat.size / 1024).toFixed(0).padStart(6)} KB → ${(after / 1024).toFixed(0).padStart(5)} KB`
    );
}

console.log(`\nsaved ${(saved / 1024 / 1024).toFixed(1)} MB across ${files.length} files`);
