import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const b=await chromium.launch({channel:'msedge',headless:true});const p=await b.newPage({viewport:{width:1440,height:900}});const errors=[],checks=[],audits=[];p.on('pageerror',e=>errors.push(e.message));
const audit=async name=>{await p.addScriptTag({path:'node_modules/axe-core/axe.min.js'});audits.push({name,violations:await p.evaluate(async()=>(await window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})))});};
await p.goto('http://127.0.0.1:5174');await p.waitForTimeout(4300);assert.equal(await p.evaluate(()=>document.body.style.overflow),'');
await p.goto('http://127.0.0.1:5174/how-it-works');
for(const label of ['Follow a detail','Respect a boundary','Notice an aside']){await p.getByRole('button',{name:label,exact:true}).click();await p.getByRole('button',{name:'See the next question',exact:true}).click();assert.ok(await p.locator('#next-question').isVisible());await p.getByRole('button',{name:'Transcript',exact:true}).click();await p.getByRole('button',{name:'Voice',exact:true}).click();assert.ok(await p.getByText('Voice preservation is planned. This text example has no recording.',{exact:true}).isVisible());}
await audit('listening proof expanded');checks.push('All three follow-up examples and memory layers');
await p.goto('http://127.0.0.1:5174');
await p.getByRole('button',{name:'Look inside',exact:true}).click();assert.match(await p.locator('.book-object img').getAttribute('src'),/open-/);checks.push('Book cover / interior state');
await p.goto('http://127.0.0.1:5174/how-it-works#calls');await p.locator('.full-call summary').click();assert.ok(await p.locator('.full-call').getAttribute('open')!==null);await p.getByRole('button',{name:'Notice an aside',exact:true}).click();assert.equal(await p.locator('.full-call').getAttribute('open'),null);
await p.getByRole('tab',{name:'The memory',exact:true}).click();await p.getByRole('button',{name:'Edit this memory',exact:true}).click();await p.getByLabel('Memory title',{exact:true}).fill('Our summer afternoon');await p.getByRole('button',{name:'Save example',exact:true}).click();assert.equal(await p.getByRole('heading',{name:'Our summer afternoon',exact:true}).count(),1);checks.push('Full script resets on selection; memory editing works');
for(const name of ['Begin','Conversation','Other voices','The archive']){await p.getByRole('tab',{name,exact:true}).click();await audit('archive '+name);}
await p.goto('http://127.0.0.1:5174/pricing');const family=p.locator('.gf-plan-row').filter({has:p.getByRole('radio',{name:'Select Family',exact:true})});await family.locator('input[type=radio]').check();await family.locator('summary').click();await family.locator('input[type=checkbox]').check();assert.match(await family.getAttribute('class'),/is-selected/);await audit('Family with book');checks.push('Family selection and book bundle');
await p.goto('http://127.0.0.1:5174/questions');await p.getByRole('searchbox').fill('xyznotananswer');assert.ok(await p.getByText('No matching answers.',{exact:false}).isVisible());await p.getByRole('searchbox').fill('privacy');assert.ok(await p.locator('.gf-faq-group').count()>0);checks.push('FAQ search and empty result');
await p.setViewportSize({width:393,height:852});await p.goto('http://127.0.0.1:5174');await p.waitForTimeout(1200);await p.screenshot({path:'qa/director/mobile-hero-final.png'});await p.getByRole('button',{name:'Menu',exact:true}).click();assert.equal(await p.locator('main').evaluate(e=>e.inert),true);await audit('Mobile menu');await p.keyboard.press('Escape');assert.equal(await p.locator('main').evaluate(e=>e.inert),false);assert.equal(await p.getByRole('button',{name:'Menu',exact:true}).evaluate(e=>e===document.activeElement),true);checks.push('Mobile menu focus, background isolation and Escape');
await p.goto('http://127.0.0.1:5174/start');await p.getByRole('button',{name:'Join the waitlist',exact:true}).click();await audit('Empty signup validation');checks.push('Signup validation (no live submission)');
for(const width of [768,1024,1728]){await p.setViewportSize({width,height:900});for(const route of ['/','/how-it-works','/pricing','/for-families','/start','/guides','/organizations','/care-communities','/our-story']){await p.goto('http://127.0.0.1:5174'+route);await p.waitForTimeout(250);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),width+' '+route);}}
checks.push('Additional 27 tablet and wide desktop layouts');assert.deepEqual(errors,[]);await writeFile('qa/director/interactions.json',JSON.stringify({checks,errors,audits},null,2));await b.close();assert.deepEqual(audits.filter(x=>x.violations.length),[]);console.log('PASS',checks,errors);
